# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plane_controller.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 554)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(10000, 10000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.action_group = QtWidgets.QGroupBox(self.centralwidget)
        self.action_group.setGeometry(QtCore.QRect(30, 10, 631, 521))
        self.action_group.setFlat(False)
        self.action_group.setObjectName("action_group")
        self.game_control_groupBox = QtWidgets.QGroupBox(self.action_group)
        self.game_control_groupBox.setGeometry(QtCore.QRect(20, 20, 301, 261))
        self.game_control_groupBox.setObjectName("game_control_groupBox")
        self.paddle_pos_6 = QtWidgets.QLabel(self.game_control_groupBox)
        self.paddle_pos_6.setGeometry(QtCore.QRect(150, 20, 101, 20))
        self.paddle_pos_6.setObjectName("paddle_pos_6")
        self.obst_fall_speed_spinbox = QtWidgets.QSpinBox(self.game_control_groupBox)
        self.obst_fall_speed_spinbox.setGeometry(QtCore.QRect(150, 40, 91, 22))
        self.obst_fall_speed_spinbox.setObjectName("obst_fall_speed_spinbox")
        self.manual_start = QtWidgets.QPushButton(self.game_control_groupBox)
        self.manual_start.setGeometry(QtCore.QRect(10, 30, 81, 61))
        self.manual_start.setObjectName("manual_start")
        self.manual_reset = QtWidgets.QPushButton(self.game_control_groupBox)
        self.manual_reset.setEnabled(False)
        self.manual_reset.setGeometry(QtCore.QRect(10, 190, 81, 41))
        self.manual_reset.setObjectName("manual_reset")
        self.timer_display = QtWidgets.QLCDNumber(self.game_control_groupBox)
        self.timer_display.setGeometry(QtCore.QRect(120, 170, 161, 71))
        self.timer_display.setObjectName("timer_display")
        self.paddle_pos_14 = QtWidgets.QLabel(self.game_control_groupBox)
        self.paddle_pos_14.setGeometry(QtCore.QRect(160, 130, 71, 31))
        self.paddle_pos_14.setObjectName("paddle_pos_14")
        self.manual_pause = QtWidgets.QPushButton(self.game_control_groupBox)
        self.manual_pause.setEnabled(False)
        self.manual_pause.setGeometry(QtCore.QRect(10, 120, 81, 41))
        self.manual_pause.setObjectName("manual_pause")
        self.paddle_pos_7 = QtWidgets.QLabel(self.game_control_groupBox)
        self.paddle_pos_7.setGeometry(QtCore.QRect(150, 80, 101, 20))
        self.paddle_pos_7.setObjectName("paddle_pos_7")
        self.obst_freq_spinbox = QtWidgets.QSpinBox(self.game_control_groupBox)
        self.obst_freq_spinbox.setGeometry(QtCore.QRect(150, 100, 91, 22))
        self.obst_freq_spinbox.setObjectName("obst_freq_spinbox")
        self.groupBox_5 = QtWidgets.QGroupBox(self.action_group)
        self.groupBox_5.setGeometry(QtCore.QRect(180, 300, 221, 201))
        self.groupBox_5.setObjectName("groupBox_5")
        self.left_dir_speed_spinbox = QtWidgets.QSpinBox(self.groupBox_5)
        self.left_dir_speed_spinbox.setGeometry(QtCore.QRect(20, 90, 71, 22))
        self.left_dir_speed_spinbox.setObjectName("left_dir_speed_spinbox")
        self.paddle_pos_28 = QtWidgets.QLabel(self.groupBox_5)
        self.paddle_pos_28.setGeometry(QtCore.QRect(30, 70, 51, 20))
        self.paddle_pos_28.setObjectName("paddle_pos_28")
        self.right_dir_speed_spinbox = QtWidgets.QSpinBox(self.groupBox_5)
        self.right_dir_speed_spinbox.setGeometry(QtCore.QRect(120, 90, 71, 22))
        self.right_dir_speed_spinbox.setObjectName("right_dir_speed_spinbox")
        self.paddle_pos_29 = QtWidgets.QLabel(self.groupBox_5)
        self.paddle_pos_29.setGeometry(QtCore.QRect(140, 70, 51, 20))
        self.paddle_pos_29.setObjectName("paddle_pos_29")
        self.reset_light = QtWidgets.QPushButton(self.groupBox_5)
        self.reset_light.setGeometry(QtCore.QRect(10, 130, 81, 31))
        self.reset_light.setObjectName("reset_light")
        self.stop_light = QtWidgets.QPushButton(self.groupBox_5)
        self.stop_light.setGeometry(QtCore.QRect(110, 130, 91, 31))
        self.stop_light.setObjectName("stop_light")
        self.single_left_shift = QtWidgets.QPushButton(self.groupBox_5)
        self.single_left_shift.setGeometry(QtCore.QRect(10, 30, 81, 31))
        self.single_left_shift.setObjectName("single_left_shift")
        self.single_right_shift = QtWidgets.QPushButton(self.groupBox_5)
        self.single_right_shift.setGeometry(QtCore.QRect(110, 30, 91, 31))
        self.single_right_shift.setObjectName("single_right_shift")
        self.RL_left_display = QtWidgets.QLabel(self.groupBox_5)
        self.RL_left_display.setGeometry(QtCore.QRect(30, 170, 71, 20))
        self.RL_left_display.setObjectName("RL_left_display")
        self.RL_right_display = QtWidgets.QLabel(self.groupBox_5)
        self.RL_right_display.setGeometry(QtCore.QRect(130, 170, 71, 20))
        self.RL_right_display.setObjectName("RL_right_display")
        self.groupBox = QtWidgets.QGroupBox(self.action_group)
        self.groupBox.setGeometry(QtCore.QRect(20, 290, 141, 211))
        self.groupBox.setObjectName("groupBox")
        self.stop_recording = QtWidgets.QPushButton(self.groupBox)
        self.stop_recording.setGeometry(QtCore.QRect(20, 130, 101, 41))
        self.stop_recording.setObjectName("stop_recording")
        self.recording_status = QtWidgets.QLabel(self.groupBox)
        self.recording_status.setGeometry(QtCore.QRect(20, 180, 121, 21))
        self.recording_status.setObjectName("recording_status")
        self.start_recording = QtWidgets.QPushButton(self.groupBox)
        self.start_recording.setGeometry(QtCore.QRect(20, 80, 101, 41))
        self.start_recording.setObjectName("start_recording")
        self.data_record_interval_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.data_record_interval_spinbox.setGeometry(QtCore.QRect(30, 40, 51, 22))
        self.data_record_interval_spinbox.setObjectName("data_record_interval_spinbox")
        self.recording_status_2 = QtWidgets.QLabel(self.groupBox)
        self.recording_status_2.setGeometry(QtCore.QRect(20, 20, 121, 21))
        self.recording_status_2.setObjectName("recording_status_2")
        self.actual_record_interval_display = QtWidgets.QLabel(self.groupBox)
        self.actual_record_interval_display.setGeometry(QtCore.QRect(90, 40, 41, 21))
        self.actual_record_interval_display.setObjectName("actual_record_interval_display")
        self.groupBox_4 = QtWidgets.QGroupBox(self.action_group)
        self.groupBox_4.setGeometry(QtCore.QRect(340, 20, 271, 261))
        self.groupBox_4.setObjectName("groupBox_4")
        self.paddle_pos_11 = QtWidgets.QLabel(self.groupBox_4)
        self.paddle_pos_11.setGeometry(QtCore.QRect(20, 50, 51, 20))
        self.paddle_pos_11.setObjectName("paddle_pos_11")
        self.paddle_pos_12 = QtWidgets.QLabel(self.groupBox_4)
        self.paddle_pos_12.setGeometry(QtCore.QRect(20, 100, 51, 20))
        self.paddle_pos_12.setObjectName("paddle_pos_12")
        self.paddle_pos_13 = QtWidgets.QLabel(self.groupBox_4)
        self.paddle_pos_13.setGeometry(QtCore.QRect(20, 150, 71, 20))
        self.paddle_pos_13.setObjectName("paddle_pos_13")
        self.x_max_spinbox = QtWidgets.QSpinBox(self.groupBox_4)
        self.x_max_spinbox.setGeometry(QtCore.QRect(90, 50, 81, 22))
        self.x_max_spinbox.setObjectName("x_max_spinbox")
        self.data_num_spinbox = QtWidgets.QSpinBox(self.groupBox_4)
        self.data_num_spinbox.setGeometry(QtCore.QRect(90, 100, 81, 22))
        self.data_num_spinbox.setObjectName("data_num_spinbox")
        self.x_coord_factor_spinbox = QtWidgets.QSpinBox(self.groupBox_4)
        self.x_coord_factor_spinbox.setGeometry(QtCore.QRect(90, 150, 81, 22))
        self.x_coord_factor_spinbox.setObjectName("x_coord_factor_spinbox")
        self.x_max_actual = QtWidgets.QLabel(self.groupBox_4)
        self.x_max_actual.setGeometry(QtCore.QRect(200, 50, 71, 20))
        self.x_max_actual.setObjectName("x_max_actual")
        self.paddle_pos_27 = QtWidgets.QLabel(self.groupBox_4)
        self.paddle_pos_27.setGeometry(QtCore.QRect(20, 200, 71, 20))
        self.paddle_pos_27.setObjectName("paddle_pos_27")
        self.torque_data_avg = QtWidgets.QLabel(self.groupBox_4)
        self.torque_data_avg.setGeometry(QtCore.QRect(120, 200, 41, 20))
        self.torque_data_avg.setObjectName("torque_data_avg")
        self.data_num_display = QtWidgets.QLabel(self.groupBox_4)
        self.data_num_display.setGeometry(QtCore.QRect(200, 100, 71, 20))
        self.data_num_display.setObjectName("data_num_display")
        self.x_coord_factor_display = QtWidgets.QLabel(self.groupBox_4)
        self.x_coord_factor_display.setGeometry(QtCore.QRect(200, 150, 71, 20))
        self.x_coord_factor_display.setObjectName("x_coord_factor_display")
        self.groupBox_6 = QtWidgets.QGroupBox(self.action_group)
        self.groupBox_6.setGeometry(QtCore.QRect(420, 300, 191, 201))
        self.groupBox_6.setObjectName("groupBox_6")
        self.simple_AI = QtWidgets.QPushButton(self.groupBox_6)
        self.simple_AI.setGeometry(QtCore.QRect(30, 30, 81, 41))
        self.simple_AI.setObjectName("simple_AI")
        self.RL_train = QtWidgets.QPushButton(self.groupBox_6)
        self.RL_train.setGeometry(QtCore.QRect(30, 150, 81, 41))
        self.RL_train.setObjectName("RL_train")
        self.AI_mode = QtWidgets.QLabel(self.groupBox_6)
        self.AI_mode.setGeometry(QtCore.QRect(130, 70, 51, 71))
        self.AI_mode.setObjectName("AI_mode")
        self.RL_test = QtWidgets.QPushButton(self.groupBox_6)
        self.RL_test.setGeometry(QtCore.QRect(30, 90, 81, 41))
        self.RL_test.setObjectName("RL_test")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.action_group.setToolTip(_translate("MainWindow", "<html><head/><body><p>控制总界面</p></body></html>"))
        self.action_group.setTitle(_translate("MainWindow", "游戏控制界面"))
        self.game_control_groupBox.setTitle(_translate("MainWindow", "控制区"))
        self.paddle_pos_6.setText(_translate("MainWindow", "障碍物下落速度:"))
        self.manual_start.setText(_translate("MainWindow", "开始"))
        self.manual_reset.setText(_translate("MainWindow", "重置"))
        self.paddle_pos_14.setText(_translate("MainWindow", "计时器(秒):"))
        self.manual_pause.setText(_translate("MainWindow", "暂停"))
        self.paddle_pos_7.setText(_translate("MainWindow", "障碍物出现间隔:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "光流单屏"))
        self.paddle_pos_28.setText(_translate("MainWindow", "左速度"))
        self.paddle_pos_29.setText(_translate("MainWindow", "右速度"))
        self.reset_light.setText(_translate("MainWindow", "重置"))
        self.stop_light.setText(_translate("MainWindow", "停止"))
        self.single_left_shift.setText(_translate("MainWindow", "左转换"))
        self.single_right_shift.setText(_translate("MainWindow", "右转换"))
        self.RL_left_display.setText(_translate("MainWindow", "RL左速度"))
        self.RL_right_display.setText(_translate("MainWindow", "RL右速度"))
        self.groupBox.setTitle(_translate("MainWindow", "数据记录"))
        self.stop_recording.setText(_translate("MainWindow", "停止记录"))
        self.recording_status.setText(_translate("MainWindow", "未记录"))
        self.start_recording.setText(_translate("MainWindow", "开始记录"))
        self.recording_status_2.setText(_translate("MainWindow", "数据记录间隔："))
        self.actual_record_interval_display.setText(_translate("MainWindow", "实际值"))
        self.groupBox_4.setTitle(_translate("MainWindow", "x位置参数："))
        self.paddle_pos_11.setText(_translate("MainWindow", "最大值: "))
        self.paddle_pos_12.setText(_translate("MainWindow", "数据量:"))
        self.paddle_pos_13.setText(_translate("MainWindow", "x坐标放大:"))
        self.x_max_actual.setText(_translate("MainWindow", "实际值"))
        self.paddle_pos_27.setText(_translate("MainWindow", "扭矩值: "))
        self.torque_data_avg.setText(_translate("MainWindow", "0"))
        self.data_num_display.setText(_translate("MainWindow", "实际值"))
        self.x_coord_factor_display.setText(_translate("MainWindow", "实际值"))
        self.groupBox_6.setTitle(_translate("MainWindow", "AI控制"))
        self.simple_AI.setText(_translate("MainWindow", "简单AI"))
        self.RL_train.setText(_translate("MainWindow", "自动调参"))
        self.AI_mode.setText(_translate("MainWindow", "AI模式"))
        self.RL_test.setText(_translate("MainWindow", "自动避障"))

